Web/Areas/Clientes/Controllers/CancelarTurnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using Aplicacion.UseCases.Cliente;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.Areas.Clientes.Models;

namespace Web.Areas.Clientes.Controllers
{

    [Area("Clientes")]
    [AllowAnonymous]
    public class CancelarTurnoController : Controller
    {

        [HttpPost]
        public IActionResult CancelarTurno(int idTurnero, int idTurno, string email, [FromServices] CancelarTurnoUC uc)
        {
            var request = new CancelarTurnoRequest
            {
                IdTurnero = idTurnero,
                IdTurno = idTurno
            };

            var response = uc.Procesar(request);

            return RedirectToAction("Index", "Home"); 
        }
    }
}

Web/Areas/Clientes/Controllers/DemorarTurnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using Aplicacion.UseCases.Cliente;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.Areas.Clientes.Models;

namespace Web.Areas.Clientes.Controllers
{

    [Area("Clientes")]
    [AllowAnonymous]
    public class DemorarTurnoController : Controller
    {

        [HttpPost]
        public IActionResult DemorarTurno(int idTurnero, int idTurno, string email, [FromServices] DemorarTurnoUC uc)
        {
            var request = new DemorarTurnoRequest
            {
                IdTurnero = idTurnero,
                IdTurno = idTurno
            };

            var response = uc.Procesar(request);

            return RedirectToAction("Detalle", "Turnos", new { idTurnero = idTurnero, idTurno = idTurno });
        }
    }
}

Web/Areas/Clientes/Controllers/TurnosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Aplicacion.UseCases.Cliente;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Web.Areas.Clientes.Models;

namespace Web.Areas.Clientes.Controllers
{
    [Area("Clientes")]
    [AllowAnonymous]
    public class TurnosController : Controller
    {
        SolicitarTurnoUC _solicitarTurnoUC;

        /*
         * Noten que para crear SolicitarTurnoUC se necesita objetos que siguen las interfaces
         *      IQRProvider 
         *      IRepositoryTurnero 
         * Las instancias concretas para esos se resuelven por el Dependency Injection de .Net Core
         * (segun se configuro en Startup.cs)
         */
        public TurnosController(SolicitarTurnoUC solicitarTurnoUC)
        {
            _solicitarTurnoUC = solicitarTurnoUC;
        }


        [HttpGet]
        public IActionResult Detalle(int idTurnero, int idTurno, [FromServices] DetallarTurnoUC detalleTurnoUC)
        {

            var request = new DetallarTurnoRequest
            {
                IdTurnero = idTurnero,
                IdTurno = idTurno
            };

            var response = detalleTurnoUC.Procesar(request);

            var turnoVM = new DetalleTurnoVM
            {
                IdTurnero = response.IdTurnero,
                Concepto = response.Concepto,
                Direccion = $"{response.Calle} {response.Numero}, {response.Ciudad}",
                Latitud = response.Latitud,
                Longitud = response.Longitud,
                IdTurno = response.IdTurno,
                Numero = response.NumeroTurno,
                EsperaEstimadaMsg = response.EsperaEstimada > 0 ? $"{response.EsperaEstimada} personas antes" : "Es tu turno!",
                Qr = response.QrTurno
            };

            return View(turnoVM);
        }

    }
}

Web/Areas/Clientes/Views/Turnos/Detalle.cshtml
@model Web.Areas.Clientes.Models.DetalleTurnoVM
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<main>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h1>Turnero @Model.Concepto</h1>
                <p>@Model.Direccion</p>

                <div id="mapaTurnero" style="height:20vh"></div>
            </div>
            <div class="col-sm-12 col-md-6">
                <div class="row justify-content-center">
                    <h1>Turno @Model.Numero</h1>
                </div>
                <div class="row justify-content-center">
                    <h2>@Model.EsperaEstimadaMsg</h2>
                </div>
                <div class="row justify-content-center">
                    <img class="img-fluid" src="data:image/jpeg;base64, @Model.Qr" alt="Codigo QR" />
                </div>
                <div class="row justify-content-center">
                    <form asp-controller="CancelarTurno">
                        <input name="idTurno" hidden value="@Model.IdTurno" />
                        <input name="idTurnero" hidden value="@Model.IdTurnero" />
                        <div class="col-sm-12">
                            <div class="btn-toolbar justify-content-around align-items-center" role="toolbar" aria-label="Toolbar with button groups">
                                <button class="btn btn-primary" type="submit" asp-controller="DemorarTurno" asp-action="DemorarTurno">Demorar turno</button>
                                <button class="btn btn-danger" type="submit" asp-controller="CancelarTurno" asp-action="CancelarTurno">Cancelar turno</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

<script src="https://openlayers.org/api/OpenLayers.js"></script>
<script>
    var Model = @Html.Raw(Json.Serialize(Model));
</script>
<script src="@Url.Content("~/Scripts/turneroInMap.js")" type="text/javascript"></script>