Web/Areas/Clientes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Clientes.Controllers
{
    [Area("Clientes")]
    [AllowAnonymous]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/Areas/Clientes/Controllers/SolicitarTurnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using Aplicacion.UseCases.Cliente;
using Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Web.Areas.Clientes.Models;

namespace Web.Areas.Clientes.Controllers
{

    [Area("Clientes")]
    [AllowAnonymous]
    public class SolicitarTurnoController : Controller
    {

        [HttpGet]
        public IActionResult Mapa([FromServices] ListarEnMapaUC uc)
        {
            var response = uc.Procesar();
            var turnerosList = response.turneros.ConvertAll(new Converter<ListarTurneroMapaDTO, ListarTurnerosVM>(ListarTurneroMapaDTOToListarTurnerosVM));

            return View(turnerosList);
        }
        
        [HttpGet]
        public IActionResult LeerQR()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ProcesarQR(string data, [FromServices] LeerQrUC leerQrUC)
        {
            
            return RedirectToAction(nameof(ConfirmarTurno), new { idTurnero = Int32.Parse(data) });
        }

        [HttpGet]
        public IActionResult ConfirmarTurno(int idTurnero, [FromServices] DetallarTurneroClienteUC uc)
        {
            var req = new DetallarTurneroClienteRequest { IdTurnero = idTurnero };
            var turneroData = uc.Procesar(req);
            return View(new ConfirmarTurnoVM(turneroData));
        }


        [HttpPost]
        public IActionResult ConfirmarTurno(int idTurnero, string email, [FromServices] SolicitarTurnoUC uc)
        {
            var request = new SolicitarTurnoRequest
            {
                IdTurnero = idTurnero,
                Email = email
            };

            var response = uc.Procesar(request);

            return RedirectToAction("Detalle", "Turnos",  new { idTurnero = response.IdTurnero, idTurno = response.IdTurno });
        }

        public static ListarTurnerosVM ListarTurneroMapaDTOToListarTurnerosVM(ListarTurneroMapaDTO turnero)
        {
            return new ListarTurnerosVM(turnero);
        }
    }
}

Web/Areas/Propietarios/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Aplicacion.UseCases.Propietario;
using Aplicacion.Interfaces;

namespace Web.Areas.Propietarios.Controllers
{
    [Area("Propietarios")]
    [Authorize]
    //[AllowAnonymous]
    public class HomeController : Controller
    {
        // GET: HomeController
        ICurrentUserService _userService;

        public HomeController(ICurrentUserService cus)
        {
            _userService = cus;
        }
        public ActionResult Index([FromServices] ListarTurnerosUC uc)
        {
            var response = uc.Procesar(new ListarTurnerosRequest { IdPropietario = _userService.UserId });
            
            return View(response.turneros);
        }
    }
}

Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Aplicacion.Exceptions;
using Aplicacion.Interfaces;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Web.Models;
using static QRCoder.PayloadGenerator;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var exceptionHandlerPathFeature = HttpContext.Features.Get<IExceptionHandlerPathFeature>();

            string ExceptionMessage = String.Empty;
            if (exceptionHandlerPathFeature?.Error is TurneroNotFoundException)
            {
                ExceptionMessage = "El turnero al que trataste de acceder no existe!";
            }
            //if (exceptionHandlerPathFeature?.Path == "/index")
            //{
            //    ExceptionMessage += " from home page";
            //}

            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier, Message = ExceptionMessage });
        }
    }
}

Web/Areas/Clientes/Views/Home/Index.cshtml
@{
    ViewData["Area"] = "Clientes";
}
<style type="text/css">
    .big-responsive-button {
        height: 20vh;
        width: 100%;
        font-size: 20px;
        text-align: center;
        border-radius: 10px;
        border: solid 1px;
        margin-bottom: 3px;
        background-color: rgb(239, 239, 239);
    }

    .big-responsive-button:hover {
        background-color: rgb(175, 175, 175);
    }
</style>

<main>
    <div class="row">
        <div class="jumbotron col-12 ">
            <div class="row flex-row flex-wrap">
                <div class="col-md-6 col-sm-12">
                    <input class="big-responsive-button" 
                           type="button"
                           value="Busca un turnero en el mapa"
                           onclick='location.href="@Url.Action("Mapa", "SolicitarTurno", new { Area = "Clientes" })"'/>  
                </div>
                <div class="col-md-6 col-sm-12">
                    <input class="big-responsive-button"
                           type="button"
                           value="Escanear un QR"
                           onclick='location.href="@Url.Action("LeerQR", "SolicitarTurno", new { Area = "Clientes" })"' />
                </div>
            </div>
        </div>
    </div>
</main>
<footer>
    <p>Si sos un propietario, entra <a asp-area="Propietarios" asp-controller="Home">aca</a></p>
</footer>