Web/Areas/Clientes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Clientes.Controllers
{
    [Area("Clientes")]
    [AllowAnonymous]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/Areas/Clientes/Controllers/TurnosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Aplicacion.UseCases.Cliente;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Web.Areas.Clientes.Models;

namespace Web.Areas.Clientes.Controllers
{
    [Area("Clientes")]
    [AllowAnonymous]
    public class TurnosController : Controller
    {
        SolicitarTurnoUC _solicitarTurnoUC;

        /*
         * Noten que para crear SolicitarTurnoUC se necesita objetos que siguen las interfaces
         *      IQRProvider 
         *      IRepositoryTurnero 
         * Las instancias concretas para esos se resuelven por el Dependency Injection de .Net Core
         * (segun se configuro en Startup.cs)
         */
        public TurnosController(SolicitarTurnoUC solicitarTurnoUC)
        {
            _solicitarTurnoUC = solicitarTurnoUC;
        }


        [HttpGet]
        public IActionResult Detalle(int idTurnero, int idTurno, [FromServices] DetallarTurnoUC detalleTurnoUC)
        {

            var request = new DetallarTurnoRequest
            {
                IdTurnero = idTurnero,
                IdTurno = idTurno
            };

            var response = detalleTurnoUC.Procesar(request);

            var turnoVM = new DetalleTurnoVM
            {
                IdTurnero = response.IdTurnero,
                Concepto = response.Concepto,
                Direccion = $"{response.Calle} {response.Numero}, {response.Ciudad}",
                Latitud = response.Latitud,
                Longitud = response.Longitud,
                IdTurno = response.IdTurno,
                Numero = response.NumeroTurno,
                EsperaEstimadaMsg = response.EsperaEstimada > 0 ? $"{response.EsperaEstimada} personas antes" : "Es tu turno!",
                Qr = response.QrTurno
            };

            return View(turnoVM);
        }

    }
}

Web/Areas/Propietarios/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Aplicacion.UseCases.Propietario;
using Aplicacion.Interfaces;

namespace Web.Areas.Propietarios.Controllers
{
    [Area("Propietarios")]
    [Authorize]
    //[AllowAnonymous]
    public class HomeController : Controller
    {
        // GET: HomeController
        ICurrentUserService _userService;

        public HomeController(ICurrentUserService cus)
        {
            _userService = cus;
        }
        public ActionResult Index([FromServices] ListarTurnerosUC uc)
        {
            var response = uc.Procesar(new ListarTurnerosRequest { IdPropietario = _userService.UserId });
            
            return View(response.turneros);
        }
    }
}

Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Aplicacion.Exceptions;
using Aplicacion.Interfaces;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Web.Models;
using static QRCoder.PayloadGenerator;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var exceptionHandlerPathFeature = HttpContext.Features.Get<IExceptionHandlerPathFeature>();

            string ExceptionMessage = String.Empty;
            if (exceptionHandlerPathFeature?.Error is TurneroNotFoundException)
            {
                ExceptionMessage = "El turnero al que trataste de acceder no existe!";
            }
            //if (exceptionHandlerPathFeature?.Path == "/index")
            //{
            //    ExceptionMessage += " from home page";
            //}

            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier, Message = ExceptionMessage });
        }
    }
}

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<div class="jumbotron">
    <h1 class="display-4">Hola!</h1>

    <a asp-area="Clientes" asp-controller="Turnos" asp-action="Nuevo" class="btn btn-primary">Solicitar turno</a>

    <img src="@ViewBag.QR" alt="Alternate Text" style="width:200px;" />

    <p>Si sos el encargado de un turnero, ingresa <a asp-area="Propietarios" asp-controller="Cuenta" asp-action="Ingresar">aca</a></p>.
</div>


<div class="">

    <form id="qr_form" asp-action="ReadQR" method="post">
        <div class="row">
            <div id="reader"></div>
        </div>
        <div class="row justify-content-center">
            <input type="text" id="qrdata" name="qrdata" hidden/>
        </div>
    </form>
</div>

<script>

    // This method will trigger user permissions
    Html5Qrcode.getCameras().then(devices => {
        /**
         * devices would be an array of objects of type:
         * { id: "id", label: "label" }
         */
        if (devices && devices.length) {
            var cameraId = devices[0].id;
            // Create instance of the object. The only argument is the "id" of HTML element created above.
            const html5QrCode = new Html5Qrcode("reader");

            html5QrCode.start(
                cameraId,     // retreived in the previous step.
                {
                    fps: 2,    // sets the framerate to 10 frame per second
                    //qrbox: 250  // sets only 250 X 250 region of viewfinder to
                    // scannable, rest shaded.
                },
                qrCodeMessage => {
                    html5QrCode.stop().then(ignore => {
                        // QR Code scanning is stopped.
                        console.log("QR Code scanning stopped.");
                    }).catch(err => {
                        // Stop failed, handle it.
                        console.log("Unable to stop scanning.");
                    });
                    // do something when code is read. For example:
                    console.log(`QR Code detected: ${qrCodeMessage}`);
                    document.getElementById("qrdata").value = qrCodeMessage;
                    document.getElementById("qr_form").submit();

                },
                errorMessage => {
                    // parse error, ideally ignore it. For example:
                    console.log(`QR Code no longer in front of camera.`);
                })
                .catch(err => {
                    // Start failed, handle it. For example,
                    console.log(`Unable to start scanning, error: ${err}`);
                });
        }
    }).catch(err => {
        console.log(err);
    });
</script>

Web/Views/Home/ReadQR.cshtml
@{
    ViewData["Title"] = "ReadQR";
}

<h1>ReadQR</h1>

<div class="justify-content-xl-center">
    @ViewBag.data
</div>